# Generated by Django 4.2.7 on 2025-10-09 04:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social del cliente', max_length=200, verbose_name='Nombre/Razón Social')),
                ('ruc_ci', models.CharField(help_text='Número de RUC o Cédula de Identidad', max_length=20, unique=True, verbose_name='RUC/CI')),
                ('direccion', models.CharField(help_text='Dirección completa del cliente', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del cliente (opcional)', max_length=254, null=True, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de la factura', max_length=20, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la factura', verbose_name='Fecha de Emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Subtotal sin IVA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Impuesto al Valor Agregado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='IVA (10%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total a pagar', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', help_text='Estado actual de la factura', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o notas adicionales', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(help_text='Cliente al que se emite la factura', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Descripción del producto o servicio', max_length=200, verbose_name='Producto/Servicio')),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Cantidad × Precio Unitario', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'ordering': ['id'],
            },
        ),
    ]
