# Generated by Django 4.2.7 on 2025-10-30 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='timbrado',
            field=models.CharField(blank=True, help_text='Número de timbrado autorizado por la SET (Paraguay)', max_length=50, null=True, verbose_name='Número de Timbrado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='timbrado_fecha',
            field=models.DateField(blank=True, help_text='Fecha desde la cual es válido el timbrado', null=True, verbose_name='Fecha de Inicio del Timbrado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='timbrado_fecha_registro',
            field=models.DateTimeField(blank=True, help_text='Cuándo se añadió el timbrado al sistema', null=True, verbose_name='Fecha de Registro del Timbrado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='timbrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el timbrado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_timbradas', to=settings.AUTH_USER_MODEL, verbose_name='Timbrado por'),
        ),
        migrations.AddField(
            model_name='factura',
            name='timbrado_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual es válido el timbrado', null=True, verbose_name='Fecha de Vencimiento del Timbrado'),
        ),
    ]
