# Generated by Django 4.2.7 on 2025-10-30 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0002_factura_timbrado_factura_timbrado_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimbradoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(help_text='Código de establecimiento (3 dígitos, ej: 001)', max_length=3, verbose_name='Establecimiento')),
                ('punto_expedicion', models.CharField(help_text='Código de punto de expedición (3 dígitos, ej: 001)', max_length=3, verbose_name='Punto de Expedición')),
                ('numero_timbrado', models.CharField(blank=True, help_text='Número de timbrado SET (opcional)', max_length=50, null=True, verbose_name='Número de Timbrado')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual es válido el timbrado', verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha hasta la cual es válido el timbrado', verbose_name='Fecha de Vencimiento')),
                ('activo', models.BooleanField(default=True, help_text='Solo puede existir una configuración activa', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Timbrado',
                'verbose_name_plural': 'Configuraciones de Timbrado',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
